[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
# startup_mode = "Maximized"
opacity = 1
# decorations = "None"
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000

[font]
size = 14
normal = { family = "BerkeleyMono Nerd Font", style = "Regular" }
# normal = { family = "FiraCode Nerd Font Mono"}
bold = { family = "BerkeleyMono Nerd Font", style = "Bold" }
italic = { family = "BerkeleyMono Nerd Font", style = "Italic" }
bold_italic = { family = "BerkeleyMono Nerd Font", style = "Bold Italic" }
offset = { x = 0, y = 3 }

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = false

[terminal]

