[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
size = 13
normal = { family = "FiraCode Nerd Font Mono"}

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

[terminal]


